# Main configuration file for Fancier Block Particles
# I advise to use the in game configuration menu instead of manually editing this file

enabled: true

# Particles Config:

minAge: 10
maxAge: 64
showInMillis: false
infiniteDuration: false
particlesPerAxis: 4
scaleMult: 0.75
gravityMult: 1.0
rotationMult: 1.0
randomRotation: true
randomizedScale: true
randomFadingSpeed: true
spawnRedstoneBlockParticles: true
spawnWhileFrozen: true
entityCollision: true
bounceOffWalls: true
lowTraction: false
smartBreaking: true
fancyFlame: true
fancySmoke: true
waterPhysics: true

# Fancy Block Placement Config:

fancyPlaceAnim: true
spawnPlaceParticles: true

# Weather Config:

fancyWeather: true
dynamicWeather: true
weatherParticleDensity: 1.0
weatherRenderDistance: 1.0

# Debug Config:

debugMode: false